plugins {
    id 'com.android.library'
}

ext {
    publishedGroupId = 'com.osama.firecrasher'
    libraryName = 'firecrasher'
    artifact = 'firecrasher'

    libraryDescription = 'a android crash handler'

    siteUrl = 'https://github.com/osama-raddad/FireCrasher'
    gitUrl = 'https://github.com/osama-raddad/FireCrasher.git'

    libraryVersion = '1.5.12'

    developerId = 'osama-raddad'
    developerName = 'osama raddad'
    developerEmail = 'osama.s.raddad@gmail.com'

    licenseName = 'The Apache Software License, Version 2.0'
    licenseUrl = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
    allLicenses = ["Apache-2.0"]
}

android {
    namespace = 'com.osama.firecrasher'
    compileSdk = 36

    defaultConfig {
        minSdk = 21
        targetSdk = 36
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
